# frozen_string_literal: true

require_relative "../../../docs_kit/version"

module DocsKit
  module Generators
    # Detects manual drift in an existing docs site that the install generator
    # can't safely automate away — things docs-kit now provides, so the site's
    # own copy is dead weight. String-level and CONSERVATIVE by design: it reads
    # a few known files, reports what it finds, and never touches a byte. The
    # generator prints these as a checklist during a `--sync` upgrade; the site
    # owner deletes the flagged code by hand.
    #
    # Drift items, from the consumer audits:
    #   - ApplicationController hand-defines `render_page` — DocsKit::Controller
    #     (included by the generator for months) already provides it.
    #   - a dead IconHelper copy — the gem renders icons via rails_icons.
    #   - a Dockerfile stamped by an OLDER docs-kit than the gem now ships — the
    #     site should diff against the current template and adopt the improvements.
    #   - a git-tracked tailwind.sources.css — generated per-build with machine
    #     absolute gem paths (#71); gitignored now, but untracking a committed
    #     copy stages a deletion, so the site runs `git rm --cached` itself.
    class SyncReport
      APPLICATION_CONTROLLER = "app/controllers/application_controller.rb"
      ICON_HELPER = "app/helpers/icon_helper.rb"
      DOCKERFILE = "Dockerfile"
      TAILWIND_SOURCES = "app/assets/stylesheets/tailwind.sources.css"

      # Matches the version stamp the Dockerfile template writes, e.g.
      # `# docs-kit Dockerfile v1.0.2`. Absent on a hand-written Dockerfile a site
      # brought itself — which we deliberately leave alone (no marker → no warning).
      DOCKERFILE_MARKER = /docs-kit Dockerfile v(\d+\.\d+\.\d+)/

      def initialize(destination_root)
        @root = destination_root
      end

      # The drift messages, in the order a site should act on them. Empty when
      # the site is clean.
      def items
        [render_page_drift, icon_helper_drift, dockerfile_drift, tailwind_sources_drift].compact
      end

      def clean?
        items.empty?
      end

      private

      # ApplicationController defines its own `render_page` — DocsKit::Controller
      # already provides it, so the hand-rolled method shadows the gem's and
      # fossilizes whatever `layout:`/render call the site copied years ago.
      def render_page_drift
        source = read(APPLICATION_CONTROLLER)
        return unless source&.match?(/def\s+render_page\b/)

        "#{APPLICATION_CONTROLLER} defines its own render_page — delete it; " \
          "DocsKit::Controller#render_page is included."
      end

      # A leftover IconHelper — docs-kit renders icons through rails_icons
      # (DocsUI::Icon), so a hand-written helper is dead code.
      def icon_helper_drift
        return unless exist?(ICON_HELPER)

        "#{ICON_HELPER} (IconHelper) is dead — docs-kit renders icons via " \
          "rails_icons (DocsUI::Icon); delete it."
      end

      # The site's Dockerfile carries a docs-kit version stamp OLDER than the gem
      # now ships. We never rewrite the site's Dockerfile (it's tuned per site) —
      # we point the owner at the current template to diff or replace. A file with
      # no marker (a hand-written Dockerfile) is left alone: no stamp, no warning.
      def dockerfile_drift
        source = read(DOCKERFILE)
        stamped = source&.match(DOCKERFILE_MARKER)
        return unless stamped

        site_version = stamped[1]
        return if site_version == DocsKit::VERSION

        "#{DOCKERFILE} is v#{site_version}, docs-kit now ships v#{DocsKit::VERSION} — " \
          "diff against the template (bin/rails g docs_kit:install shows the path) and adopt the changes."
      end

      # tailwind.sources.css is regenerated by bin/build-css with machine-local
      # absolute gem paths — the generator gitignores it, but a copy committed
      # before the ignore stays tracked (gitignore doesn't untrack). Untracking
      # stages a deletion, so we hand the site the exact command instead of
      # touching its index.
      def tailwind_sources_drift
        return unless tracked_by_git?(TAILWIND_SOURCES)

        "#{TAILWIND_SOURCES} is generated by bin/build-css but tracked by git — " \
          "run `git rm --cached #{TAILWIND_SOURCES}` and commit (the ignore entry is in place)."
      end

      # True when the site's git index tracks `rel`. Conservative: no git on
      # PATH, not a repo, or an untracked file all read as "no drift". ls-files
      # only consults the index (no commit needed), and `git -C` resolves the
      # repo upward, so a docs site living in a subdir of a larger repo works.
      def tracked_by_git?(rel)
        system("git", "-C", @root, "ls-files", "--error-unmatch", rel,
               out: File::NULL, err: File::NULL) == true
      end

      def read(rel)
        path = File.join(@root, rel)
        File.exist?(path) ? File.read(path) : nil
      end

      def exist?(rel) = File.exist?(File.join(@root, rel))
    end
  end
end
